[workspace]
resolver = "2"
members = ["minigolf", "minigolf_client", "minigolf_lobby", "minigolf_server"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Valters Melnalksnis"]

[workspace.dependencies]
bevy = { version = "0.18.1", default-features = false }
bevy_egui = { version = "0.39.1", default-features = true }
bevy-inspector-egui = { version = "0.36.0", default-features = true }
egui = { version = "0.33.3" }
egui_dock = { version = "0.18.0" }

bevy_replicon = { version = "0.39.1", default-features = false }

avian3d = { version = "0.6.0", default-features = false }

aeronet = { git = "https://github.com/liamaharon/aeronet.git", branch = "bevy_replicon_0.39" }
aeronet_websocket = { git = "https://github.com/liamaharon/aeronet.git", branch = "bevy_replicon_0.39", default-features = false }
aeronet_webtransport = { git = "https://github.com/liamaharon/aeronet.git", branch = "bevy_replicon_0.39", default-features = false }
aeronet_replicon = { git = "https://github.com/liamaharon/aeronet.git", branch = "bevy_replicon_0.39", default-features = false }

serde = "1.0.228"
serde_json = "1.0.149"

clap = "4.6.0"

web-sys = { version = "0.3.91", default-features = false }
uuid = { version = "1.22.0", default-features = false }
rand = { version = "0.10.0", default-features = true }
getrandom = { version = "0.4.2", default-features = true }

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "fat"

# Optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web.
[profile.wasm-release]
# Default to release profile values.
inherits = "release"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "z"
# Strip all debugging information from the binary to slightly reduce file size.
strip = "debuginfo"
